version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_foldershare
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: foldershare
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql

  


volumes:
  mysql-data:
